### PR TITLE
Bump node to 18

### PR DESCRIPTION
**Pull request by cortinico**

### CODE REVIEW

**Comment by elicwhite** [comment]
Does LTS (20) not work?

**Comment by cortinico** [comment]
Pretty equivalent but 20 is probably better. I just wanted to unblock as the sync hss been broken for 2 months 👍

**Comment by elicwhite** [comment]
Oh. I didn't realize that was the problem with the sync. I thought it was due to another issue. Sure, merging

**Comment by elicwhite** [comment]
Yeah, triggered a new build. This is the error I got months ago before the node version issue:

```
fatal: Unable to find refs/remotes/origin/chrome/m119 revision in submodule path 'externals/skia'
fatal: Failed to recurse into submodule path 'Shopify/react-native-skia'

    at ChildProcess.exithandler (node:child_process:4[22](https://github.com/TheSavior/react-native-libraries/actions/runs/7593304311/job/20683638141#step:5:23):12)
    at ChildProcess.emit (node:events:517:28)
    at maybeClose (node:internal/child_process:1098:16)
    at ChildProcess._handle.onexit (node:internal/child_process:303:5) {
    ```
    
    I'm not sure why though because I don't get that error when I run locally. 
    
    I'll manually push an update regardless though.

**Comment by cortinico** [comment]
@TheSavior Seems like the latest automatic update worked fine 👍

**Comment by elicwhite** [comment]
I switched the CI to not recursively install, which is what probably caused that react-native-skia issue (perhaps because chrome/m119 is on a host other than github?). So it's possible that the CI isn't doing anything anymore. We should know in a few days.

**Pull request merged**
